### ISSUE TITLE
How to use rodemirror without @codemirror/basic-setup as I don't want some functionalities included in it?

### ISSUE THREAD

**Issue by SatyamKr07** [sachinraja/rodemirror#46]
First of all, thanks for creating this package! It is helping a lot.
Now as I don't want some features like code folding which is enabled by default. Is there a way to disable it? Or how to use only selected features from basic-setup for rodemirror?

**Comment by sachinraja** [comment]
> which is enabled by default

Nothing is enabled by default. This package only wraps CodeMirror for use in React. All the examples use `@codemirror/basic-setup` because it is the easiest way to setup a functioning editor. If you don't want to use it, you can select your own plugins (see https://codemirror.net/6/docs/ref/#basic-setup).
